CUDA_VISIBLE_DEVICES=0,1 python -m domainbed.scripts.train\
    --algorithm Clip_train_distributed\
    --data_dir /home/sanoojan.baliah/project/dataset/DG/ \
    --dataset TerraIncognita\
    --holdout_fraction 0.2\
    --hparams '{"weight_init":"clip_full","backbone":"Large","lr":0.000005,"batch_size":16 }'\
    --hparams_seed 0\
    --output_dir ./domainbed/outputs/check/e4d590ed8bd92a7ea53c5688aa0201c7\
    --seed 216093517\
    --task domain_generalization\
    --test_envs 0\
    --trial_seed 0\
    --checkpoint_freq 2500\
    --wandbname Terra-test_check_delete